backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/uploads" # Media files will be stored here


collections:
  - label: "Homepage Sections"
    name: "sections"
    files:
      - label: "Hero"
        name: "hero"
        file: "collections/_sections/hero.md"
        fields:
          - {label: Title, name: heading, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Buttons
            name: "buttons"
            widget: "list"
            fields: 
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "link", widget: "string", default: "#"}
  - name: "events" 
    label: "Events" 
    folder: "collections/_events" 
    create: true 
    slug: "{{slug}}" 
    identifier_field: name
    fields: 
      - {label: "Name", name: "name", widget: "text", required: true}
      - {label: "Subtitle", name: "subtitle", widget: "text", required: true}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Image", name: "banner", widget: "image", required: true }
      - {label: "Short Name", name: "shortName", widget: "hidden", default: "{{slug}}"}

