backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/uploads" # Media files will be stored here


collections:
  - label: "Homepage Sections"
    name: "sections"
    files:
      - label: "Hero"
        name: "hero"
        file: "collections/_sections/hero.md"
        fields:
          - {label: Title, name: heading, widget: string}
          - {label: Image, name: image, widget: string, default: "assets/images/hero/hero.jpg"}
          - label: Buttons
            name: "buttons"
            widget: "list"
            fields: 
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "link", widget: "string", default: "#"}
      - label: "About"
        name: "about"
        file: "collections/_sections/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: text}
          - label: Values
            name: values
            widget: list
          - label: Stats
            name: stats
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Value, name: value, widget: number}
          - label: Button
            name: "button"
            widget: "object"
            fields: 
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "link", widget: "string", default: "#"}
      - label: "Events"
        name: "events"
        file: "collections/_sections/events.md"
        fields:
          - {label: Title, name: header, widget: string}
          - {label: Subtitle, name: subheader, widget: string}
          - {label: Link, name: link, widget: string}
          - label: Events
            name: "events"
            widget: "list"
            fields: 
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Thumnbail", name: "thumbnail", widget: "image", default: "#"}
          - {label: "Footer Heading", name: footer, widget: string}
          - {label: "Footer Link Text", name: footer-link-text, widget: string}
          - {label: Footer Link, name: footer-link-text, widget: string}
          - label: Footer Button
            name: "footer-button"
            widget: "object"
            fields: 
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "link", widget: "string", default: "#"}