backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/uploads" # Media files will be stored here


collections:
  - label: "Homepage Sections"
    name: "sections"
    files:
      - label: "Hero"
        name: "about"
        file: "collections/_sections/hero.md"
        fields:
          - {label: Title, name: heading, widget: string}
          - {label: Image, name: image, widget: string, default: "assets/images/hero/hero.jpg"}
          - label: Buttons
            name: "buttons"
            widget: "list"
            fields: 
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "link", widget: "string", default: "#"}
      - label: "About"
        name: "about"
        file: "collections/_sections/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: text}
          - label: Values
            name: values
            widget: list
          - label: Stats
            name: stats
            widget: list
            fields:
              - {label: Label, name: string, widget: string}
              - {label: Value, name: value, widget: number}
          - label: Button
            name: "button"
            widget: "object"
            fields: 
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "link", widget: "string", default: "#"}
