backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/uploads" # Media files will be stored here


collections:
  - label: "Homepage Sections"
    name: "sections"
    files:
      - label: "Hero"
        name: "about"
        file: "collections/_sections/hero.md"
        fields:
          - {label: Title, name: heading, widget: string}
          - {label: Image, name: image, widget: string, default: "assets/images/hero/hero.jpg"}
          - label: Buttons
            name: "buttons"
            widget: "list"
            fields: 
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "link", widget: "string", default: "#"}
      - label: "About"
        name: "about"
        file: "collections/_sections/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: text}
          - label: Values
            name: values
            widget: list
          - label: Stats
            name: stats
            widget: list
            fields:
              - {label: Label, name: string, widget: string}
              - {label: Value, name: value, widget: number}
          - label: Button
            name: "button"
            widget: "object"
            fields: 
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "link", widget: "string", default: "#"}
      - label: "Events"
        name: "events"
        file: "collections/_sections/events.md"
        fields:
          - {label: Title, name: heading, widget: string}
          - {label: Subtitle, name: subheading, widget: string}
          - {label: Link, name: link, widget: string}
          - {label: Image, name: image, widget: string, default: "assets/images/hero/hero.jpg"}
          - label: Events
            name: "events"
            widget: "list"
            fields: 
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Thumnbail", name: "thumbnail", widget: "image", default: "#"}
          - {label: Footer Heading, name: footer, widget: string}
          - {label: Footer Link Text, name: footer-link-text, widget: string}
          - {label: Footer Link, name: footer-link-text, widget: string}
          - label: Footer Button
            name: "footer-button"
            widget: "object"
            fields: 
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "link", widget: "string", default: "#"}

  # - name: "products" 
  #   label: "Products" 
  #   folder: "_products/" 
  #   create: true 
  #   identifier_field: name
  #   slug: "{{slug}}" 
  #   fields: 
  #     - {label: "Name", name: "name", widget: "text", required: true}
  #     - {label: "Description", name: "description", widget: "text", required: true}
  #     - {label: "Image", name: "image", widget: "image", required: true}
  #     - {label: "Price", name: "price", widget: "text", required: true}
  #     - {label: "Purchase URL", name: "purchase-url", widget: "string", required: false, default: '#'}
  #     - {label: "Display Category", name: "category", widget: "relation", collection: "categories", searchFields: ["name", "link"], valueField: "name", displayFields: ["name", "link"]}
  #     - {label: "Functional Category", name: "category-link", widget: "relation", collection: "categories", searchFields: ["name", "link"], valueField: "link", displayFields: ["name", "link"]}
  #     #- {label: "Display Category", name: "category", widget: "relation", collection: "categories", searchFields: "name", valueFields: "name", required: false}

  #     #- {label: "Functional Category", name: "category-link", widget: "relation", collection: "categories", searchFields: "name", valueFields: "link", required: false}

